-- Creación de usuarios.
INSERT INTO users(username, password, avatar, tier, description, authority, birth_date, enable)
VALUES ('alesanfe', 'patata', 'https://i.pinimg.com/736x/bd/33/43/bd3343e3e4e13c58e408c79f0e029b75.jpg', 0,
        'I want a nap', 'DOKTOL', '2002-02-01', 1),
       ('antonio', 'patata', 'https://i.pinimg.com/736x/bd/33/43/bd3343e3e4e13c58e408c79f0e029b75.jpg', 0,
        'I am a description', 'USER', '2002-02-01', 1);
('laurolmer', 'patata', 'https://i.pinimg.com/736x/bd/33/43/bd3343e3e4e13c58e408c79f0e029b75.jpg', 0, 'awanabumbambam', 'USER', '2002-08-21', 1)
,
('alvhidrod', 'patata', 'https://i.pinimg.com/736x/bd/33/43/bd3343e3e4e13c58e408c79f0e029b75.jpg', 0, 'drakorion', 'USER', '2002-02-23', 1)
,
('ismruijur', 'patata', 'https://i.pinimg.com/736x/bd/33/43/bd3343e3e4e13c58e408c79f0e029b75.jpg', 0, 'er jefe brrr', 'USER', '2002-10-27', 1)
,
('ivasansan1', 'patata', 'https://i.pinimg.com/736x/bd/33/43/bd3343e3e4e13c58e408c79f0e029b75.jpg', 0, 'bético encubierto', 'USER', '2002-11-12', 1)
,
('pedruiagu', 'patata', 'https://i.pinimg.com/736x/bd/33/43/bd3343e3e4e13c58e408c79f0e029b75.jpg', 0, 'sácame del bolsillo', 'USER', '2002-10-01', 1);

-- Creación de mensajes.
INSERT INTO messages(content, time, receiver_id, sender_id)
VALUES ('Hola, soy Alesanfe', '2020-02-01 12:00', 1, 2),
       ('Hola, soy Antonio', '2020-02-01 12:00', 2, 1);

<<<<<<<<< Temporary merge branch 1
INSERT INTO message(id, content, time, receiver_id, sender_id)
VALUES (1, 'Hola, soy Alesanfe', '2020-02-01 12:00:00', 1, 2),
       (2, 'Hola, soy Antonio', '2020-02-01 12:00:00', 2, 1);

=========
>>>>>>>>> Temporary merge branch 2
-- Creación de capacidades.
INSERT INTO capacities(state_capacity, less_damage)
VALUES ('MELEE', false),
       ('RANGE', false),
       ('MAGIC', false),
       ('EXPERTISE', false),
       ('MELEE', true),
       ('RANGE', true),
       ('MAGIC', true),
       ('EXPERTISE', true);

<<<<<<<<< Temporary merge branch 1
-- Héroes
INSERT INTO heroes(id, name, frontImage, backImage, timesUsed, aux, health, role, deck, hand, discard, enemies, capacities)
VALUES (1, 'Valèrys', 'src/main/resources/static/resources/images/heroes/valerys_hero_front.png', 'src/main/resources/static/resources/images/heroes/lisavette_hero_back.png', 0, 0, 3, KNIGHT, ?, ?, ?, ?, MELEE),
       (2, 'Lisavette', 'src/main/resources/static/resources/images/heroes/lisavette_hero_back.png', 'src/main/resources/static/resources/images/heroes/valerys_hero_front.png', 0, 0, 3, KNIGHT, ?, ?, ?, ?, MELEE),
       (3, 'Beleth-Il', 'src/main/resources/static/resources/images/heroes/belethil_hero_front.png', 'src/main/resources/static/resources/images/heroes/idril_hero_back.png', 0, 0, 3, EXPLORER, ?, ?, ?, ?, RANGED, MELEE),
       (4, 'Idril', 'src/main/resources/static/resources/images/heroes/idril_hero_back.png', 'src/main/resources/static/resources/images/heroes/belethil_hero_front.png', 0, 0, 3, EXPLORER, ?, ?, ?, ?, [RANGED, MELEE]),
       (5, 'Neddia', 'src/main/resources/static/resources/images/heroes/neddia_hero_back.png', 'src/main/resources/static/resources/images/heroes/feldon_hero_front.png', 0, 0, 2, THIEF, ?, ?, ?, ?, [EXPERTISE, RANGED]),
       (4, 'Feldon', 'src/main/resources/static/resources/images/heroes/feldon_hero_back.png', 'src/main/resources/static/resources/images/heroes/neddia_hero_front.png', 0, 0, 2, THIEF, ?, ?, ?, ?, [EXPERTISE, RANGED]),
       (4, 'Aranel', 'src/main/resources/static/resources/images/heroes/aranel_hero_back.png', 'src/main/resources/static/resources/images/heroes/taheral_hero_front.png', 0, 0, 2, WIZARD, ?, ?, ?, ?, [MAGIC]),
       (4, 'Taheral', 'src/main/resources/static/resources/images/heroes/taheral_hero_back.png', 'src/main/resources/static/resources/images/heroes/aranel_hero_front.png', 0, 0, 2, WIZARD, ?, ?, ?, ?, [MAGIC]);

-- Productos
INSERT INTO products(id, name, frontImage, backImage, timesUsed, aux, price, attack, ability, capacity)
VALUES (1, 'Daga élfica', 'src/main/resources/static/resources/images/products/dagaelfica_product_front.png', 'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 3, 2, ?, [RANGED, MELEE, EXPERTISE, MAGIC]),
       (2, 'Daga élfica', 'src/main/resources/static/resources/images/products/dagaelfica_product_front.png', 'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 3, 2, ?, [RANGED, MELEE, EXPERTISE, MAGIC]),
       (3, 'Poción curativa', 'src/main/resources/static/resources/images/products/pocioncurativa_product_front.png', 'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 8, 0, ?, [RANGED, MELEE, EXPERTISE, MAGIC]),
       (4, 'Poción curativa', 'src/main/resources/static/resources/images/products/pocioncurativa_product_front.png', 'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 8, 0, ?, [RANGED, MELEE, EXPERTISE, MAGIC]),
       (5, 'Poción curativa', 'src/main/resources/static/resources/images/products/pocioncurativa_product_front.png', 'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 8, 0, ?, [RANGED, MELEE, EXPERTISE, MAGIC]),
       (6, 'Piedra de amolar', 'src/main/resources/static/resources/images/products/piedraamolar_product_front.png', 'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 4, 0, ?, [RANGED, MELEE, EXPERTISE]),
       (7, 'Vial de conjuración', 'src/main/resources/static/resources/images/products/vialconjuracion_product_front.png', 'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 5, 0, ?, [RANGED, MELEE, EXPERTISE, MAGIC]),
       (8, 'Vial de conjuración', 'src/main/resources/static/resources/images/products/vialconjuracion_product_front.png', 'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 5, 0, ?, [RANGED, MELEE, EXPERTISE, MAGIC]),
       (9, 'Elixir de concentración', 'src/main/resources/static/resources/images/products/pocioncurativa_product_front.png', 'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 3, 0, ?, [RANGED, MELEE, EXPERTISE, MAGIC]),
       (10, 'Elixir de concentración', 'src/main/resources/static/resources/images/products/pocioncurativa_product_front.png', 'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 3, 0, ?, [RANGED, MELEE, EXPERTISE, MAGIC]),
       (11, 'Capa élfica', 'src/main/resources/static/resources/images/products/capaelfica_product_front.png', 'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 3, 0, ?, [RANGED, MAGIC]),
       (12, 'Armadura de placas', 'src/main/resources/static/resources/images/products/armaduraplacas_product_front.png', 'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 4, 0, ?, [MELEE]),
       (13, 'Alabarda orca', 'src/main/resources/static/resources/images/products/alabardaorca_product_front.png', 'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 5, 4, ?, [MELEE]),
       (14, 'Arco compuesto', 'src/main/resources/static/resources/images/products/arcocompuesto_product_front.png', 'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 5, 4, ?, [RANGED]);

-- Ability
INSERT INTO abilities(id, name, frontImage, backImage, timesUsed, aux, role, attack)
VALUES (1, 'Aura protectora', 'src/main/resources/static/resources/images/abilities/auraprotectora_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 0),
       (2, 'Bola de fuego', 'src/main/resources/static/resources/images/abilities/boladefuego_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 2),
       (3, 'Disparo gélido', 'src/main/resources/static/resources/images/abilities/disparogelido_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 1),
       (4, 'Disparo gélido', 'src/main/resources/static/resources/images/abilities/disparogelido_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 1),
       (5, 'Flecha corrosiva', 'src/main/resources/static/resources/images/abilities/flechacorrosiva_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 1),
       (6, 'Golpe de bastón', 'src/main/resources/static/resources/images/abilities/golpebaston_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 1),
       (7, 'Golpe de bastón', 'src/main/resources/static/resources/images/abilities/golpebaston_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 1),
       (8, 'Golpe de bastón', 'src/main/resources/static/resources/images/abilities/golpebaston_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 1),
       (9, 'Golpe de bastón', 'src/main/resources/static/resources/images/abilities/golpebaston_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 1),
       (10, 'Orbe curativo', 'src/main/resources/static/resources/images/abilities/orbecurativo_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 0),
       (11, 'Proyectil ígneo', 'src/main/resources/static/resources/images/abilities/proyectiligneo_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 2),
       (12, 'Proyectil ígneo', 'src/main/resources/static/resources/images/abilities/proyectiligneo_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 2),
       (13, 'Proyectil ígneo', 'src/main/resources/static/resources/images/abilities/proyectiligneo_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 2),
       (14, 'Reconstitución', 'src/main/resources/static/resources/images/abilities/reconstitucion_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 0),
       (15, 'Torrente de luz', 'src/main/resources/static/resources/images/abilities/torrentedeluz_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 2),
       (16, 'Al corazón', 'src/main/resources/static/resources/images/abilities/alcorazon_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 4),
       (17, 'Al corazón', 'src/main/resources/static/resources/images/abilities/alcorazon_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 4),
       (18, 'Ataque furtivo', 'src/main/resources/static/resources/images/abilities/ataquefurtivo_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 2),
       (19, 'Ataque furtivo', 'src/main/resources/static/resources/images/abilities/ataquefurtivo_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 2),
       (20, 'Ataque furtivo', 'src/main/resources/static/resources/images/abilities/ataquefurtivo_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 2),
       (21, 'Ballesta precisa', 'src/main/resources/static/resources/images/abilities/ballestaprecisa_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 2),
       (22, 'Ballesta precisa', 'src/main/resources/static/resources/images/abilities/ballestaprecisa_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 2),
       (23, 'Ballesta precisa', 'src/main/resources/static/resources/images/abilities/ballestaprecisa_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 2),
       (24, 'En las sombras', 'src/main/resources/static/resources/images/abilities/enlassombras_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 1),
       (25, 'En las sombras', 'src/main/resources/static/resources/images/abilities/enlassombras_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 1),
       (26, 'Engañar', 'src/main/resources/static/resources/images/abilities/engañar_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 0),
       (27, 'Robar bolsillo', 'src/main/resources/static/resources/images/abilities/robarbolsillos_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 0),
       (28, 'Saqueo', 'src/main/resources/static/resources/images/abilities/saqueo_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 0),
       (29, 'Saqueo', 'src/main/resources/static/resources/images/abilities/saqueo_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 0),
       (30, 'Trampa', 'src/main/resources/static/resources/images/abilities/trampa_ability_front.png', 'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 0);

=========
-- Creación de habilidades.
INSERT INTO abilities(name, front_image, back_image, role, attack, hero_id)
VALUES ('Compañero Lobo', 'src/main/resources/static/resources/images/juego/wolf_abilities_front.png',
        'src/main/resources/static/resources/images/juego/parte_atras_general.png', 'EXPLORER', 2),
       ('Disparo Certero', 'src/main/resources/static/resources/images/juego/sharp_abilities_front.png',
        'src/main/resources/static/resources/images/juego/parte_atras_general.png', 'EXPLORER', 3),
       ('Disparo Rápido', 'src/main/resources/static/resources/images/juego/rapid_abilities_front.png',
        'src/main/resources/static/resources/images/juego/parte_atras_general.png', 'EXPLORER', 1),
       ('En la Diana', 'src/main/resources/static/resources/images/juego/diana_abilities_front.png',
        'src/main/resources/static/resources/images/juego/parte_atras_general.png', 'EXPLORER', 4),
       ('Lluvia de flechas', 'src/main/resources/static/resources/images/juego/rain_abilities_front.png',
        'src/main/resources/static/resources/images/juego/parte_atras_general.png', 'EXPLORER', 2),
       ('Recoger flechas', 'src/main/resources/static/resources/images/juego/pick_abilities_front.png',
        'src/main/resources/static/resources/images/juego/parte_atras_general.png', 'EXPLORER', 0),
       ('Supervivencia', 'src/main/resources/static/resources/images/juego/survival_abilities_front.png',
        'src/main/resources/static/resources/images/juego/parte_atras_general.png', 'EXPLORER', 0),
       ('Ataque Brutal', 'src/main/resources/static/resources/images/juego/brutal_abilities_front.png',
        'src/main/resources/static/resources/images/juego/parte_atras_general.png', 'KNIGHT', 3),
       ('Carga con Escudo', 'src/main/resources/static/resources/images/juego/charge_abilities_front.png',
        'src/main/resources/static/resources/images/juego/parte_atras_general.png', 'KNIGHT', 2),
       ('Doble Espadazo', 'src/main/resources/static/resources/images/juego/doble_abilities_front.png',
        'src/main/resources/static/resources/images/juego/parte_atras_general.png', 'KNIGHT', 2),
       ('Escudo', 'src/main/resources/static/resources/images/juego/shield_abilities_front.png',
        'src/main/resources/static/resources/images/juego/parte_atras_general.png', 'KNIGHT', 0),
       ('Espadazo', 'src/main/resources/static/resources/images/juego/sword_abilities_front.png',
        'src/main/resources/static/resources/images/juego/parte_atras_general.png', 'KNIGHT', 1),
       ('Paso Atrás', 'src/main/resources/static/resources/images/juego/back_abilities_front.png',
        'src/main/resources/static/resources/images/juego/parte_atras_general.png', 'KNIGHT', 0),
       ('Todo o Nada', 'src/main/resources/static/resources/images/juego/all_abilities_front.png',
        'src/main/resources/static/resources/images/juego/parte_atras_general.png', 'KNIGHT', 1),
       ('Voz de Aliento', 'src/main/resources/static/resources/images/juego/AAAAAAAA_abilities_front.png',
        'src/main/resources/static/resources/images/juego/parte_atras_general.png', 'KNIGHT', 0),
       ('Aura protectora', 'src/main/resources/static/resources/images/abilities/auraprotectora_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 0),
       ('Bola de fuego', 'src/main/resources/static/resources/images/abilities/boladefuego_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 2),
       ('Disparo gélido', 'src/main/resources/static/resources/images/abilities/disparogelido_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 1),
       ('Disparo gélido', 'src/main/resources/static/resources/images/abilities/disparogelido_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 1),
       ('Flecha corrosiva', 'src/main/resources/static/resources/images/abilities/flechacorrosiva_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 1),
       ('Golpe de bastón', 'src/main/resources/static/resources/images/abilities/golpebaston_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 1),
       ('Golpe de bastón', 'src/main/resources/static/resources/images/abilities/golpebaston_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 1),
       ('Golpe de bastón', 'src/main/resources/static/resources/images/abilities/golpebaston_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 1),
       ('Golpe de bastón', 'src/main/resources/static/resources/images/abilities/golpebaston_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 1),
       ('Orbe curativo', 'src/main/resources/static/resources/images/abilities/orbecurativo_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 0),
       ('Proyectil ígneo', 'src/main/resources/static/resources/images/abilities/proyectiligneo_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 2),
       ('Proyectil ígneo', 'src/main/resources/static/resources/images/abilities/proyectiligneo_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 2),
       ('Proyectil ígneo', 'src/main/resources/static/resources/images/abilities/proyectiligneo_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 2),
       ('Reconstitución', 'src/main/resources/static/resources/images/abilities/reconstitucion_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 0),
       ('Torrente de luz', 'src/main/resources/static/resources/images/abilities/torrentedeluz_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, WIZARD, 2),
       ('Al corazón', 'src/main/resources/static/resources/images/abilities/alcorazon_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 4),
       ('Al corazón', 'src/main/resources/static/resources/images/abilities/alcorazon_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 4),
       ('Ataque furtivo', 'src/main/resources/static/resources/images/abilities/ataquefurtivo_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 2),
       ('Ataque furtivo', 'src/main/resources/static/resources/images/abilities/ataquefurtivo_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 2),
       ('Ataque furtivo', 'src/main/resources/static/resources/images/abilities/ataquefurtivo_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 2),
       ('Ballesta precisa', 'src/main/resources/static/resources/images/abilities/ballestaprecisa_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 2),
       ('Ballesta precisa', 'src/main/resources/static/resources/images/abilities/ballestaprecisa_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 2),
       ('Ballesta precisa', 'src/main/resources/static/resources/images/abilities/ballestaprecisa_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 2),
       ('En las sombras', 'src/main/resources/static/resources/images/abilities/enlassombras_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 1),
       ('En las sombras', 'src/main/resources/static/resources/images/abilities/enlassombras_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 1),
       ('Engañar', 'src/main/resources/static/resources/images/abilities/engañar_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 0),
       ('Robar bolsillo', 'src/main/resources/static/resources/images/abilities/robarbolsillos_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 0),
       ('Saqueo', 'src/main/resources/static/resources/images/abilities/saqueo_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 0),
       ('Saqueo', 'src/main/resources/static/resources/images/abilities/saqueo_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 0),
       ('Trampa', 'src/main/resources/static/resources/images/abilities/trampa_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 0, 1, THIEF, 0);

-- Creación de orcos.
INSERT INTO orcs(name, back_image, front_image, health, glory, gold, has_cure, less_damage_wizard)
VALUES ('Honda', 'src/main/resources/static/resources/images/juego/0-0_orc_back.png',
        'src/main/resources/static/resources/images/juego/honda_orc_front.png', 2, 1, 0, FALSE, FALSE),
       ('Honda', 'src/main/resources/static/resources/images/juego/1-0_orc_back.png',
        'src/main/resources/static/resources/images/juego/honda_orc_front.png', 2, 1, 1, FALSE, FALSE),
       ('Honda', 'src/main/resources/static/resources/images/juego/1-0_orc_back.png',
        'src/main/resources/static/resources/images/juego/honda_orc_front.png', 2, 1, 1, FALSE, FALSE),
       ('Honda', 'src/main/resources/static/resources/images/juego/0-0_orc_back.png',
        'src/main/resources/static/resources/images/juego/honda_orc_front.png', 2, 1, 0, FALSE, FALSE),
       ('Honda', 'src/main/resources/static/resources/images/juego/1-0_orc_back.png',
        'src/main/resources/static/resources/images/juego/honda_orc_front.png', 2, 1, 1, FALSE, FALSE),
       ('Lanza', 'src/main/resources/static/resources/images/juego/0-0_orc_back.png',
        'src/main/resources/static/resources/images/juego/lanza_orc_front.png', 3, 2, 0, TRUE, FALSE),
       ('Lanza', 'src/main/resources/static/resources/images/juego/0-0_orc_back.png',
        'src/main/resources/static/resources/images/juego/lanza_orc_front.png', 3, 2, 0, TRUE, FALSE),
       ('Lanza', 'src/main/resources/static/resources/images/juego/0-0_orc_back.png',
        'src/main/resources/static/resources/images/juego/lanza_orc_front.png', 3, 2, 0, TRUE, FALSE),
       ('Lanza', 'src/main/resources/static/resources/images/juego/1-0_orc_back.png',
        'src/main/resources/static/resources/images/juego/lanza_orc_front.png', 3, 2, 1, TRUE, FALSE),
       ('Lanza', 'src/main/resources/static/resources/images/juego/1-1_orc_back.png',
        'src/main/resources/static/resources/images/juego/chaman_orc_front.png', 3, 3, 1, TRUE, FALSE),
       ('Chaman', 'src/main/resources/static/resources/images/juego/2-0_orc_back.png',
        'src/main/resources/static/resources/images/juego/chaman_orc_front.png', 3, 1, 2, FALSE, TRUE),
       ('Chaman', 'src/main/resources/static/resources/images/juego/0-0_orc_back.png',
        'src/main/resources/static/resources/images/juego/chaman_orc_front.png', 3, 1, 0, FALSE, TRUE),
       ('Sword', 'src/main/resources/static/resources/images/juego/0-0_orc_back.png',
        'src/main/resources/static/resources/images/juego/sword_orc_front.png', 4, 2, 0, FALSE, FALSE),
       ('Sword', 'src/main/resources/static/resources/images/juego/0-0_orc_back.png',
        'src/main/resources/static/resources/images/juego/sword_orc_front.png', 4, 2, 0, FALSE, FALSE),
       ('Sword', 'src/main/resources/static/resources/images/juego/1-0_orc_back.png',
        'src/main/resources/static/resources/images/juego/sword_orc_front.png', 4, 2, 1, FALSE, FALSE),
       ('Sword', 'src/main/resources/static/resources/images/juego/1-0_orc_back.png',
        'src/main/resources/static/resources/images/juego/bounty_orc_front.png', 4, 2, 1, FALSE, FALSE),
       ('Sword', 'src/main/resources/static/resources/images/juego/1-0_orc_back.png',
        'src/main/resources/static/resources/images/juego/bounty_orc_front.png', 4, 2, 1, FALSE, FALSE),
       ('Sword', 'src/main/resources/static/resources/images/juego/2-0_orc_back.png',
        'src/main/resources/static/resources/images/juego/bounty_orc_front.png', 4, 2, 2, FALSE, FALSE),
       ('Sword', 'src/main/resources/static/resources/images/juego/2-1_orc_back.png',
        'src/main/resources/static/resources/images/juego/bounty_orc_front.png', 4, 3, 2, FALSE, FALSE),
       ('Sword', 'src/main/resources/static/resources/images/juego/2-1_orc_back.png',
        'src/main/resources/static/resources/images/juego/bounty_orc_front.png', 4, 3, 2, FALSE, FALSE),
       ('Gran Chaman', 'src/main/resources/static/resources/images/juego/0-0_orc_back.png',
        'src/main/resources/static/resources/images/juego/greatchaman_orc_front.png', 5, 3, 0, FALSE, TRUE),
       ('Gran Chaman', 'src/main/resources/static/resources/images/juego/2-0_orc_back.png',
        'src/main/resources/static/resources/images/juego/greatchaman_orc_front.png', 5, 3, 2, FALSE, TRUE),
       ('Gran Chaman', 'src/main/resources/static/resources/images/juego/2-0_orc_back.png',
        'src/main/resources/static/resources/images/juego/greatchaman_orc_front.png', 5, 3, 2, FALSE, TRUE),
       ('Gran Chaman', 'src/main/resources/static/resources/images/juego/2-1_orc_back.png',
        'src/main/resources/static/resources/images/juego/greatchaman_orc_front.png', 5, 4, 2, FALSE, TRUE),
       ('Terminator', 'src/main/resources/static/resources/images/juego/1-0_orc_back.png',
        'src/main/resources/static/resources/images/juego/axe_orc_front.png', 6, 4, 0, FALSE, FALSE),
       ('Terminator', 'src/main/resources/static/resources/images/juego/1-0_orc_back.png',
        'src/main/resources/static/resources/images/juego/axe_orc_front.png', 6, 4, 0, FALSE, FALSE),
       ('Terminator', 'src/main/resources/static/resources/images/juego/0-0_orc_back.png',
        'src/main/resources/static/resources/images/juego/axe_orc_front.png', 6, 4, 1, FALSE, FALSE);


-- Creación de señores de la noche.
INSERT INTO night_lords(name, back_image, front_image, health)
VALUES ('Gurdrug', 'src/main/resources/static/resources/images/juego/nightlord_back.png',
        'src/main/resources/static/resources/images/juego/gur_nightlord_front.png', 8),
       ('Roghkiller', 'src/main/resources/static/resources/images/juego/nightlord_back.png',
        'src/main/resources/static/resources/images/juego/rogh_nightlord_front.png', 9),
       ('Shriekknifer', 'src/main/resources/static/resources/images/juego/nightlord_back.png',
        'src/main/resources/static/resources/images/juego/shriek_nightlord_front.png', 10);

-- Creación de héroes.
INSERT INTO heroes(id, name, frontImage, backImage, timesUsed, aux, health, role, deck, hand, discard, enemies,
                   capacities)
VALUES (1, 'Valèrys', 'src/main/resources/static/resources/images/heroes/valerys_hero_front.png',
        'src/main/resources/static/resources/images/heroes/lisavette_hero_back.png', 0, 0, 3, KNIGHT, ?, ?, ?, ?,
        MELEE),
       (2, 'Lisavette', 'src/main/resources/static/resources/images/heroes/lisavette_hero_back.png',
        'src/main/resources/static/resources/images/heroes/valerys_hero_front.png', 0, 0, 3, KNIGHT, ?, ?, ?, ?, MELEE),
       (3, 'Beleth-Il', 'src/main/resources/static/resources/images/heroes/belethil_hero_front.png',
        'src/main/resources/static/resources/images/heroes/idril_hero_back.png', 0, 0, 3, EXPLORER, ?, ?, ?, ?, RANGED,
        MELEE),
       (4, 'Idril', 'src/main/resources/static/resources/images/heroes/idril_hero_back.png',
        'src/main/resources/static/resources/images/heroes/belethil_hero_front.png', 0, 0, 3, EXPLORER, ?, ?, ?, ?, [RANGED,
        MELEE]),
       (5, 'Neddia', 'src/main/resources/static/resources/images/heroes/neddia_hero_back.png',
        'src/main/resources/static/resources/images/heroes/feldon_hero_front.png', 0, 0, 2, THIEF, ?, ?, ?, ?, [EXPERTISE,
        RANGED]),
       (4, 'Feldon', 'src/main/resources/static/resources/images/heroes/feldon_hero_back.png',
        'src/main/resources/static/resources/images/heroes/neddia_hero_front.png', 0, 0, 2, THIEF, ?, ?, ?, ?, [EXPERTISE,
        RANGED]),
       (4, 'Aranel', 'src/main/resources/static/resources/images/heroes/aranel_hero_back.png',
        'src/main/resources/static/resources/images/heroes/taheral_hero_front.png', 0, 0, 2, WIZARD, ?, ?, ?,
        ?, [MAGIC]),
       (4, 'Taheral', 'src/main/resources/static/resources/images/heroes/taheral_hero_back.png',
        'src/main/resources/static/resources/images/heroes/aranel_hero_front.png', 0, 0, 2, WIZARD, ?, ?, ?,
        ?, [MAGIC]);

-- Productos
INSERT INTO products(id, name, frontImage, backImage, timesUsed, aux, price, attack, ability, capacity)
VALUES (1, 'Daga élfica', 'src/main/resources/static/resources/images/products/dagaelfica_product_front.png',
        'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 3, 2, ?, [RANGED, MELEE,
        EXPERTISE, MAGIC]),
       (2, 'Daga élfica', 'src/main/resources/static/resources/images/products/dagaelfica_product_front.png',
        'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 3, 2, ?, [RANGED, MELEE,
        EXPERTISE, MAGIC]),
       (3, 'Poción curativa', 'src/main/resources/static/resources/images/products/pocioncurativa_product_front.png',
        'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 8, 0, ?, [RANGED, MELEE,
        EXPERTISE, MAGIC]),
       (4, 'Poción curativa', 'src/main/resources/static/resources/images/products/pocioncurativa_product_front.png',
        'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 8, 0, ?, [RANGED, MELEE,
        EXPERTISE, MAGIC]),
       (5, 'Poción curativa', 'src/main/resources/static/resources/images/products/pocioncurativa_product_front.png',
        'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 8, 0, ?, [RANGED, MELEE,
        EXPERTISE, MAGIC]),
       (6, 'Piedra de amolar', 'src/main/resources/static/resources/images/products/piedraamolar_product_front.png',
        'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 4, 0, ?, [RANGED, MELEE,
        EXPERTISE]),
       (7, 'Vial de conjuración',
        'src/main/resources/static/resources/images/products/vialconjuracion_product_front.png',
        'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 5, 0, ?, [RANGED, MELEE,
        EXPERTISE, MAGIC]),
       (8, 'Vial de conjuración',
        'src/main/resources/static/resources/images/products/vialconjuracion_product_front.png',
        'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 5, 0, ?, [RANGED, MELEE,
        EXPERTISE, MAGIC]),
       (9, 'Elixir de concentración',
        'src/main/resources/static/resources/images/products/pocioncurativa_product_front.png',
        'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 3, 0, ?, [RANGED, MELEE,
        EXPERTISE, MAGIC]),
       (10, 'Elixir de concentración',
        'src/main/resources/static/resources/images/products/pocioncurativa_product_front.png',
        'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 3, 0, ?, [RANGED, MELEE,
        EXPERTISE, MAGIC]),
       (11, 'Capa élfica', 'src/main/resources/static/resources/images/products/capaelfica_product_front.png',
        'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 3, 0, ?, [RANGED, MAGIC]),
       (12, 'Armadura de placas',
        'src/main/resources/static/resources/images/products/armaduraplacas_product_front.png',
        'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 4, 0, ?, [MELEE]),
       (13, 'Alabarda orca', 'src/main/resources/static/resources/images/products/alabardaorca_product_front.png',
        'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 5, 4, ?, [MELEE]),
       (14, 'Arco compuesto', 'src/main/resources/static/resources/images/products/arcocompuesto_product_front.png',
        'src/main/resources/static/resources/images/products/product_back.png', 0, 0, 5, 4, ?, [RANGED]);

-- Ability
INSERT INTO abilities(id, name, frontImage, backImage, timesUsed, aux, role, attack)
VALUES
>>>>>>>>> Temporary merge branch 2
