-- Creación de usuarios.
INSERT INTO users(username, password, avatar, tier, description, authority, birth_date, enable)
VALUES ('alesanfe', 'patata', 'https://i.pinimg.com/736x/bd/33/43/bd3343e3e4e13c58e408c79f0e029b75.jpg', 0,
        'I want a nap', 'DOKTOL', '2002-02-01', 1),
       ('antonio', 'patata', 'https://i.pinimg.com/736x/bd/33/43/bd3343e3e4e13c58e408c79f0e029b75.jpg', 0,
        'I am a description', 'USER', '2002-02-01', 1),
       ('laurolmer', 'patata', 'https://i.pinimg.com/736x/bd/33/43/bd3343e3e4e13c58e408c79f0e029b75.jpg', 0,
        'awanabumbambam', 'USER', '2002-08-21', 1),
       ('alvhidrod', 'patata', 'https://i.pinimg.com/736x/bd/33/43/bd3343e3e4e13c58e408c79f0e029b75.jpg', 0,
        'drakorion', 'USER', '2002-02-23', 1),
       ('ismruijur', 'patata', 'https://i.pinimg.com/736x/bd/33/43/bd3343e3e4e13c58e408c79f0e029b75.jpg', 0,
        'er jefe brrr', 'USER', '2002-10-27', 1),
       ('ivasansan1', 'patata', 'https://i.pinimg.com/736x/bd/33/43/bd3343e3e4e13c58e408c79f0e029b75.jpg', 0,
        'betico encubierto', 'USER', '2002-11-12', 1),
       ('pedruiagu', 'patata', 'https://i.pinimg.com/736x/bd/33/43/bd3343e3e4e13c58e408c79f0e029b75.jpg', 0,
        'sacame del bolsillo', 'USER', '2002-10-01', 1);

-- Creación de mensajes.
INSERT INTO messages(content, time, receiver_id, sender_id)
VALUES ('Hola, soy Alesanfe', '2020-02-01 12:00', 1, 2),
       ('Hola, soy Antonio', '2020-02-01 12:00', 2, 1);

-- Creación de capacidades.
INSERT INTO capacities(state_capacity, less_damage)
VALUES ('MELEE', false),
       ('RANGE', false),
       ('MAGIC', false),
       ('EXPERTISE', false),
       ('MELEE', true),
       ('RANGE', true),
       ('MAGIC', true),
       ('EXPERTISE', true);

-- Creación de héroes.
INSERT INTO heroes(name, front_image, back_image, health, role)
VALUES ('Valerys', 'src/main/resources/static/resources/images/heroes/valerys_hero_front.png',
        'src/main/resources/static/resources/images/heroes/lisavette_hero_back.png', 3, 'KNIGHT'),
       ('Lisavette', 'src/main/resources/static/resources/images/heroes/lisavette_hero_back.png',
        'src/main/resources/static/resources/images/heroes/valerys_hero_front.png', 3, 'KNIGHT'),
       ('Beleth-Il', 'src/main/resources/static/resources/images/heroes/belethil_hero_front.png',
        'src/main/resources/static/resources/images/heroes/idril_hero_back.png', 3, 'EXPLORER'),
       ('Idril', 'src/main/resources/static/resources/images/heroes/idril_hero_back.png',
        'src/main/resources/static/resources/images/heroes/belethil_hero_front.png', 3, 'EXPLORER'),
       ('Neddia', 'src/main/resources/static/resources/images/heroes/neddia_hero_back.png',
        'src/main/resources/static/resources/images/heroes/feldon_hero_front.png', 2, 'THIEF'),
       ('Feldon', 'src/main/resources/static/resources/images/heroes/feldon_hero_back.png',
        'src/main/resources/static/resources/images/heroes/neddia_hero_front.png', 2, 'THIEF'),
       ('Aranel', 'src/main/resources/static/resources/images/heroes/aranel_hero_back.png',
        'src/main/resources/static/resources/images/heroes/taheral_hero_front.png', 2, 'WIZARD'),
       ('Taheral', 'src/main/resources/static/resources/images/heroes/taheral_hero_back.png',
        'src/main/resources/static/resources/images/heroes/aranel_hero_front.png', 2, 'WIZARD');

-- Creación de habilidades.
INSERT INTO abilities(name, front_image, back_image, role, attack, quantity)
VALUES ('Compañero Lobo', 'src/main/resources/static/resources/images/abilities/wolf_abilities_front.png',
        'src/main/resources/static/resources/images/abilities/parte_atras_general.png', 'EXPLORER', 2, 1),
       ('Disparo Certero', 'src/main/resources/static/resources/images/abilities/sharp_abilities_front.png',
        'src/main/resources/static/resources/images/abilities/parte_atras_general.png', 'EXPLORER', 3, 1),
       ('Disparo Rapido', 'src/main/resources/static/resources/images/juego/rapid_abilities_front.png',
        'src/main/resources/static/resources/images/abilities/parte_atras_general.png', 'EXPLORER', 1, 1),
       ('En La Diana', 'src/main/resources/static/resources/images/abilities/diana_abilities_front.png',
        'src/main/resources/static/resources/images/abilities/parte_atras_general.png', 'EXPLORER', 4, 1),
       ('Lluvia De Flechas', 'src/main/resources/static/resources/images/abilities/rain_abilities_front.png',
        'src/main/resources/static/resources/images/abilities/parte_atras_general.png', 'EXPLORER', 2, 1),
       ('Recoger Flechas', 'src/main/resources/static/resources/images/abilities/pick_abilities_front.png',
        'src/main/resources/static/resources/images/abilities/parte_atras_general.png', 'EXPLORER', 0, 1),
       ('Supervivencia', 'src/main/resources/static/resources/images/abilities/survival_abilities_front.png',
        'src/main/resources/static/resources/images/abilities/parte_atras_general.png', 'EXPLORER', 0, 1),
       ('Ataque Brutal', 'src/main/resources/static/resources/images/abilities/brutal_abilities_front.png',
        'src/main/resources/static/resources/images/abilities/parte_atras_general.png', 'KNIGHT', 3, 1),
       ('Carga Con Escudo', 'src/main/resources/static/resources/images/abilities/charge_abilities_front.png',
        'src/main/resources/static/resources/images/abilities/parte_atras_general.png', 'KNIGHT', 2, 1),
       ('Doble Espadazo', 'src/main/resources/static/resources/images/abilities/doble_abilities_front.png',
        'src/main/resources/static/resources/images/abilities/parte_atras_general.png', 'KNIGHT', 2, 1),
       ('Escudo', 'src/main/resources/static/resources/images/abilities/shield_abilities_front.png',
        'src/main/resources/static/resources/images/abilities/parte_atras_general.png', 'KNIGHT', 0, 1),
       ('Espadazo', 'src/main/resources/static/resources/images/abilities/sword_abilities_front.png',
        'src/main/resources/static/resources/images/abilities/parte_atras_general.png', 'KNIGHT', 1, 1),
       ('Paso Atras', 'src/main/resources/static/resources/images/abilities/back_abilities_front.png',
        'src/main/resources/static/resources/images/abilities/parte_atras_general.png', 'KNIGHT', 0, 1),
       ('Todo O Nada', 'src/main/resources/static/resources/images/abilities/all_abilities_front.png',
        'src/main/resources/static/resources/images/abilities/parte_atras_general.png', 'KNIGHT', 1, 1),
       ('Voz De Aliento', 'src/main/resources/static/resources/images/abilities/AAAAAAAA_abilities_front.png',
        'src/main/resources/static/resources/images/abilities/parte_atras_general.png', 'KNIGHT', 0, 1),
       ('Aura Protectora', 'src/main/resources/static/resources/images/abilities/auraprotectora_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 'WIZARD', 0, 1),
       ('Bola De Fuego', 'src/main/resources/static/resources/images/abilities/boladefuego_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 'WIZARD', 2, 1),
       ('Disparo Gelido', 'src/main/resources/static/resources/images/abilities/disparogelido_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 'WIZARD', 1, 2),
       ('Flecha Corrosiva', 'src/main/resources/static/resources/images/abilities/flechacorrosiva_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 'WIZARD', 1, 1),
       ('Golpe De Baston', 'src/main/resources/static/resources/images/abilities/golpebaston_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 'WIZARD', 1, 3),
       ('Orbe Curativo', 'src/main/resources/static/resources/images/abilities/orbecurativo_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 'WIZARD', 0, 1),
       ('Proyectil Igneo', 'src/main/resources/static/resources/images/abilities/proyectiligneo_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 'WIZARD', 2, 1),
       ('Reconstitucion', 'src/main/resources/static/resources/images/abilities/reconstitucion_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 'WIZARD', 0, 1),
       ('Torrente De Luz', 'src/main/resources/static/resources/images/abilities/torrentedeluz_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 'WIZARD', 2, 1),
       ('Al Corazon', 'src/main/resources/static/resources/images/abilities/alcorazon_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 'THIEF', 4, 1),
       ('Ataque Furtivo', 'src/main/resources/static/resources/images/abilities/ataquefurtivo_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 'THIEF', 2, 1),
       ('Ballesta Precisa', 'src/main/resources/static/resources/images/abilities/ballestaprecisa_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 'THIEF', 2, 2),
       ('En Las Sombras', 'src/main/resources/static/resources/images/abilities/enlassombras_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 'THIEF', 1, 1),
       ('Engañar', 'src/main/resources/static/resources/images/abilities/engañar_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 'THIEF', 0, 1),
       ('Robar Bolsillo', 'src/main/resources/static/resources/images/abilities/robarbolsillos_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 'THIEF', 0, 1),
       ('Saqueo', 'src/main/resources/static/resources/images/abilities/saqueo_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 'THIEF', 0, 1),
       ('Trampa', 'src/main/resources/static/resources/images/abilities/trampa_ability_front.png',
        'src/main/resources/static/resources/images/abilities/ability_back.png', 'THIEF', 0, 1);

-- Creación de orcos.
INSERT INTO orcs(name, back_image, front_image, health, glory, gold, has_cure, less_damage_wizard)
VALUES ('Honda', 'src/main/resources/static/resources/images/orcs/0-0_orc_back.png',
        'src/main/resources/static/resources/images/orcs/honda_orc_front.png', 2, 1, 0, FALSE, FALSE),
       ('Honda', 'src/main/resources/static/resources/images/orcs/1-0_orc_back.png',
        'src/main/resources/static/resources/images/orcs/honda_orc_front.png', 2, 1, 1, FALSE, FALSE),
       ('Honda', 'src/main/resources/static/resources/images/orcs/1-0_orc_back.png',
        'src/main/resources/static/resources/images/orcs/honda_orc_front.png', 2, 1, 1, FALSE, FALSE),
       ('Honda', 'src/main/resources/static/resources/images/orcs/0-0_orc_back.png',
        'src/main/resources/static/resources/images/orcs/honda_orc_front.png', 2, 1, 0, FALSE, FALSE),
       ('Honda', 'src/main/resources/static/resources/images/orcs/1-0_orc_back.png',
        'src/main/resources/static/resources/images/orcs/honda_orc_front.png', 2, 1, 1, FALSE, FALSE),
       ('Lanza', 'src/main/resources/static/resources/images/orcs/0-0_orc_back.png',
        'src/main/resources/static/resources/images/orcs/lanza_orc_front.png', 3, 2, 0, TRUE, FALSE),
       ('Lanza', 'src/main/resources/static/resources/images/orcs/0-0_orc_back.png',
        'src/main/resources/static/resources/images/orcs/lanza_orc_front.png', 3, 2, 0, TRUE, FALSE),
       ('Lanza', 'src/main/resources/static/resources/images/orcs/0-0_orc_back.png',
        'src/main/resources/static/resources/images/orcs/lanza_orc_front.png', 3, 2, 0, TRUE, FALSE),
       ('Lanza', 'src/main/resources/static/resources/images/orcs/1-0_orc_back.png',
        'src/main/resources/static/resources/images/orcs/lanza_orc_front.png', 3, 2, 1, TRUE, FALSE),
       ('Lanza', 'src/main/resources/static/resources/images/v/1-1_orc_back.png',
        'src/main/resources/static/resources/images/orcs/chaman_orc_front.png', 3, 3, 1, TRUE, FALSE),
       ('Chaman', 'src/main/resources/static/resources/images/orcs/2-0_orc_back.png',
        'src/main/resources/static/resources/images/orcs/chaman_orc_front.png', 3, 1, 2, FALSE, TRUE),
       ('Chaman', 'src/main/resources/static/resources/images/orcs/0-0_orc_back.png',
        'src/main/resources/static/resources/images/orcs/chaman_orc_front.png', 3, 1, 0, FALSE, TRUE),
       ('Espadachin', 'src/main/resources/static/resources/images/orcs/0-0_orc_back.png',
        'src/main/resources/static/resources/images/orcs/sword_orc_front.png', 4, 2, 0, FALSE, FALSE),
       ('Espadachin', 'src/main/resources/static/resources/images/orcs/0-0_orc_back.png',
        'src/main/resources/static/resources/images/orcs/sword_orc_front.png', 4, 2, 0, FALSE, FALSE),
       ('Espadachin', 'src/main/resources/static/resources/images/orcs/1-0_orc_back.png',
        'src/main/resources/static/resources/images/orcs/sword_orc_front.png', 4, 2, 1, FALSE, FALSE),
       ('Espadachin', 'src/main/resources/static/resources/images/orcs/1-0_orc_back.png',
        'src/main/resources/static/resources/images/orcs/bounty_orc_front.png', 4, 2, 1, FALSE, FALSE),
       ('Espadachin', 'src/main/resources/static/resources/images/orcs/1-0_orc_back.png',
        'src/main/resources/static/resources/images/orcs/bounty_orc_front.png', 4, 2, 1, FALSE, FALSE),
       ('Espadachin', 'src/main/resources/static/resources/images/orcs/2-0_orc_back.png',
        'src/main/resources/static/resources/images/orcs/bounty_orc_front.png', 4, 2, 2, FALSE, FALSE),
       ('Espadachin', 'src/main/resources/static/resources/images/orcs/2-1_orc_back.png',
        'src/main/resources/static/resources/images/orcs/bounty_orc_front.png', 4, 3, 2, FALSE, FALSE),
       ('Espadachin', 'src/main/resources/static/resources/images/orcs/2-1_orc_back.png',
        'src/main/resources/static/resources/images/orcs/bounty_orc_front.png', 4, 3, 2, FALSE, FALSE),
       ('Gran Chaman', 'src/main/resources/static/resources/images/orcs/0-0_orc_back.png',
        'src/main/resources/static/resources/images/orcs/greatchaman_orc_front.png', 5, 3, 0, FALSE, TRUE),
       ('Gran Chaman', 'src/main/resources/static/resources/images/juego/2-0_orc_back.png',
        'src/main/resources/static/resources/images/orcs/greatchaman_orc_front.png', 5, 3, 2, FALSE, TRUE),
       ('Gran Chaman', 'src/main/resources/static/resources/images/juego/2-0_orc_back.png',
        'src/main/resources/static/resources/images/orcs/greatchaman_orc_front.png', 5, 3, 2, FALSE, TRUE),
       ('Gran Chaman', 'src/main/resources/static/resources/images/juego/2-1_orc_back.png',
        'src/main/resources/static/resources/images/orcs/greatchaman_orc_front.png', 5, 4, 2, FALSE, TRUE),
       ('Terminator', 'src/main/resources/static/resources/images/orcs/1-0_orc_back.png',
        'src/main/resources/static/resources/images/orcs/axe_orc_front.png', 6, 4, 0, FALSE, FALSE),
       ('Terminator', 'src/main/resources/static/resources/images/orcs/1-0_orc_back.png',
        'src/main/resources/static/resources/images/orcs/axe_orc_front.png', 6, 4, 0, FALSE, FALSE),
       ('Terminator', 'src/main/resources/static/resources/images/orcs/0-0_orc_back.png',
        'src/main/resources/static/resources/images/orcs/axe_orc_front.png', 6, 4, 1, FALSE, FALSE);

-- Creación de señores de la noche.
INSERT INTO night_lords(name, back_image, front_image, health)
VALUES ('Gurdrug', 'src/main/resources/static/resources/images/nightlords/nightlord_back.png',
        'src/main/resources/static/resources/images/nightlords/gur_nightlord_front.png', 8),
       ('Roghkiller', 'src/main/resources/static/resources/images/nightlords/nightlord_back.png',
        'src/main/resources/static/resources/images/nightlords/rogh_nightlord_front.png', 9),
       ('Shriekknifer', 'src/main/resources/static/resources/images/nightlords/nightlord_back.png',
        'src/main/resources/static/resources/images/nightlords/shriek_nightlord_front.png', 10);

-- Productos
INSERT INTO products(name, front_image, back_image, price, attack, quantity)
VALUES ('Daga Elfica', 'src/main/resources/static/resources/images/products/dagaelfica_product_front.png',
        'src/main/resources/static/resources/images/products/product_back.png', 3, 2, 2),
       ('Pocion Curativa', 'src/main/resources/static/resources/images/products/pocioncurativa_product_front.png',
        'src/main/resources/static/resources/images/products/product_back.png', 8, 0, 3),
       ('Piedra De Amolar', 'src/main/resources/static/resources/images/products/piedraamolar_product_front.png',
        'src/main/resources/static/resources/images/products/product_back.png', 4, 0, 1),
       ('Vial De Conjuracion',
        'src/main/resources/static/resources/images/products/vialconjuracion_product_front.png',
        'src/main/resources/static/resources/images/products/product_back.png', 5, 0, 2),
       ('Elixir De Concentracion',
        'src/main/resources/static/resources/images/products/pocioncurativa_product_front.png',
        'src/main/resources/static/resources/images/products/product_back.png', 3, 0, 2),
       ('Capa Elfica', 'src/main/resources/static/resources/images/products/capaelfica_product_front.png',
        'src/main/resources/static/resources/images/products/product_back.png', 3, 0, 1),
       ('Armadura De Placas',
        'src/main/resources/static/resources/images/products/armaduraplacas_product_front.png',
        'src/main/resources/static/resources/images/products/product_back.png', 4, 0, 1),
       ('Alabarda Orca', 'src/main/resources/static/resources/images/products/alabardaorca_product_front.png',
        'src/main/resources/static/resources/images/products/product_back.png', 5, 4, 1),
       ('Arco Compuesto', 'src/main/resources/static/resources/images/products/arcocompuesto_product_front.png',
        'src/main/resources/static/resources/images/products/product_back.png', 5, 4, 1);

-- Habilidades de los heroes
INSERT INTO heroes_abilities(hero_id, abilities_id)
VALUES (1, 8), (1, 9), (1, 10), (1, 11), (1, 12), (1, 13), (1, 14), (1, 15),
       (2, 8), (2, 9), (2, 10), (2, 11), (2, 12), (2, 13), (2, 14), (2, 15),
       (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7),
       (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7),
       (5, 16), (5, 17), (5, 18), (5, 19), (5, 20), (5, 21), (5, 22), (5, 23), (5, 24),
       (6, 16), (6, 17), (6, 18), (6, 19), (6, 20), (6, 21), (6, 22), (6, 23), (6, 24),
       (7, 25), (7, 26), (7, 27), (7, 28), (7, 29), (7, 30), (7, 31), (7, 32),
       (8, 25), (8, 26), (8, 27), (8, 28), (8, 29), (8, 30), (8, 31), (8, 32);

-- Capacidades de los heroes
INSERT INTO heroes_capacities(hero_id, capacities_id)
VALUES (1, 1),
       (2, 1),
       (3, 2), (3, 5),
       (4, 2), (4, 5),
       (5, 4), (5, 6),
       (6, 4), (6, 6),
       (7, 3),
       (8, 3);
